[package]
name = "linkedslab"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
# Nothing

[dev-dependencies]
criterion = "0.3.2"
rand = "0.7"

[[bench]]
name = "benches"
path = "benches/main.rs"
harness = false